
services:
  frontend:
    build: ./frontend
    image: src/frontend
    container_name: frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_BACKEND_URL: "http://backend:8000" 
    ports:
      - "3000:3000"  
    networks:
      - app-network
    depends_on:
      - backend  

  backend:
    build: ./backend
    image: src/backend
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"  
    container_name: backend
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
